# Generated by Django 5.0.1 on 2026-01-17 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deputy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deputies',
            },
        ),
        migrations.CreateModel(
            name='DeputyConstituency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='deputies.deputy')),
            ],
            options={
                'db_table': 'deputy_constituencies',
            },
        ),
        migrations.CreateModel(
            name='DeputySpecialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('specialization', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('infrastructure', 'Infrastructure'), ('economy', 'Economy'), ('social_affairs', 'Social Affairs'), ('environment', 'Environment'), ('law', 'Law and Order'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='deputies.deputy')),
            ],
            options={
                'db_table': 'deputy_specializations',
            },
        ),
    ]
