# Generated by Django 5.0.1 on 2026-01-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deputies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputyconstituency',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deputyspecialization',
            options={'ordering': ['-is_primary', 'specialization']},
        ),
    ]
