# Generated by Django 5.0.1 on 2026-01-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_constituency_citizen_constituency'),
        ('deputies', '0002_alter_deputyconstituency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputy',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputies', to='citizens.constituency'),
        ),
    ]
