# Generated by Django 5.0.1 on 2026-02-01 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('citizen', 'Citizen'), ('deputy', 'Deputy'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_citizen', models.BooleanField(default=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_messages', to='appeals.appeal')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['appeal', 'created_at'], name='appeals_app_appeal__d024ff_idx'), models.Index(fields=['sender_type'], name='appeals_app_sender__daa70d_idx')],
            },
        ),
    ]
