FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./

RUN npm ci

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
