# Generated by Django 5.0.1 on 2026-01-31 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_alter_citizen_address_alter_citizen_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'db_table': 'constituencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='citizen',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='citizens.constituency'),
        ),
    ]
