# Generated by Django 5.0.1 on 2026-01-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260129_1225'),
    ]

    operations = [
        # First, update existing empty phone values to NULL
        migrations.RunSQL(
            "UPDATE users SET phone = NULL WHERE phone = '';",
            reverse_sql="UPDATE users SET phone = '' WHERE phone IS NULL;"
        ),
        # Then, alter the field to allow NULL values
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, unique=True, null=True, blank=True),
        ),
    ]
